### ISSUE TITLE
컨테이너로 실행 시 "no such file or directory" 에러 발생

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-apigw#48]
@ccambomorris 한 번 확인을 부탁드립니다.. ^^

**What happened**
: 
0.3.2 컨테이너 이미지 (PR #43 & #45 의 변경사항을 포함함) 실행 시 에러가 발생합니다.
```
❯ docker logs 97d31cb1fd5d
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

0.3.3 컨테이너 이미지 (PR #47 의 변경사항을 포함함) 도 동일 증상입니다.

**What you expected to happen**
: 
cb-restapigw 컨테이너가 정상적으로 실행됨

**How to reproduce it (as minimally and precisely as possible)**
: 

1. cb-apigw repo 최신 소스 클론 (<= PR #47 의 변경사항을 포함함)
2. `cd cb-apigw`
3. `docker-compose up --build`

```
etri_grafana exited with code 1
etri_apigw exited with code 1
```

```
❯ docker logs 97d31cb1fd5d
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Anything else we need to know?**
: 
cb-operator 를 이용했을 때에도 동일 증상입니다.

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:
"no such file or directory" 에러가 뜰 때
어떤 파일이 없는건지 보여준다면 파악이 좀 더 쉽고 빠를 것 같습니다.. :)

**Comment by ccambomorris** [comment]
오류 발생 메시지를 확인해 보니 cb-apigw 루트 경로의 docker-compose 를 사용하시고 계시는군요.
저는 계속 cb-apigw/restapigw/deploy/docker-compose 기준으로 작업을 했었습니다.

따라서 루트의 docker-compose.yaml 파일은 현재 restapigw/deploy/docker-compose.yaml 에 적용된 내용과 다른 것 같습니다.
이전 PR 적용한 후에는 이런 오류가 없이 정상적으로 작동을 했었던것인가요?

etri_apigw exited with code 1 이 발생하는 것을 확인했고 logs에 오류 메시지도 확인했습니다.
전 etri_grafana exited with code 1 은 발생하지 않았습니다.

일단 발생한 오류는 컨테이너가 구동 되었지만 애플리케이션 구동을 위한 파일이나 경로를 못 찾는 상황으로 cb-restapigw 가 컨테이너 내부에서 실행되지도 않은 상태입니다.

왜 이런 상황이 발생하는지 Dockerfile 과 docker-compose 관련된 내용들을 검토해 봐야 할 것 같습니다.

우선 이번 PR의 기능상의 검증을 위해서는 cb-apigw/restapigw/deploy/docker-compose.yaml 을 기준으로 검토해 주시면 좋겠습니다.

확인되는데로 다시 PR 올리도록 하겠습니다.

PS. 최상위 폴더 (cb-apigw) 에 대한 자료들을 모두 현재 버전에 맞도록 정리를 해야할 것 같습니다.

**Comment by ccambomorris** [comment]
오류 검증을 해 본 결과 cb-apigw/restapigw/Dockerfile 의 Golang Compile Option이 누락되어 Linux에서 인식할 수 없는 형식으로 컴파일이 된 것 같습니다.

- Dockerfile 및 docker-compose.yaml 파일 수정
- InfluxDB 및 Grafana 관련 수정

상기와 같이 처리해서 로컬 기준으로 docker-compose 동작을 확인했습니다.

다만, cb-apigw 의 README.md 의 내용 중에서 RESTAPIGW 의 내용은 cb-apigw/restapigw/README.md 파일의 내용으로 교체를 하여야 할 것 같은데.. cb-apigw 는 향후 gRPC 관련된 내용도 추가가 될 것이니 링크 형식으로 처리하는게 맞는 것 같습니다.

검토해 보시고 이상한 상황이나 또 다른 문제가 있다면 알려주시기 바랍니다.

테스트를 하셔야 하니 문서관련된 내용은 향후 결정되면 반영하도록 하고 일단 변경된 내용은 PR로 올리도록 하겠습니다.

**Comment by seokho-son** [comment]
Cc @jihoon-seo

**Comment by jihoon-seo** [comment]
- Resolved by #49
