### ISSUE TITLE
Grafana 컨테이너가 Permission denied 문제로 종료됨

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-apigw#50]
@ccambomorris 한 번 확인을 부탁드립니다.. ^^

**What happened**
: 
Grafana 컨테이너가 Permission denied 문제로 종료됨

**What you expected to happen**
: 
Grafana 컨테이너가 잘 실행됨

**How to reproduce it (as minimally and precisely as possible)**
: 
https://github.com/cloud-barista/cb-apigw/tree/master/restapigw/deploy#%EC%8B%A4%ED%96%89-%EB%B0%A9%EB%B2%95
여기에 나와 있는 대로
`cb-apigw/restapigw/deploy` 디렉토리에서
```
docker-compose up --build
```
를 실행하니
grafana 컨테이너가 종료됩니다.

```
❯ docker ps -a | grep grafana
cdc68df708c3        grafana/grafana:7.4.5                          "/run.sh"                28 seconds ago      Exited (1) 27 seconds ago

❯ docker logs cdc68df708c3
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

**Anything else we need to know?**
: 

**Environment**
- cb-apigw source code version: #49 가 반영된 최신 버전 (8b3d980)
- `grafana/grafana` 컨테이너 이미지 버전: 7.2.1 & 7.4.5 (Why 7.4.5? => #45)
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:
- `grafana/grafana` 컨테이너 이미지 7.2.1 과 7.4.5 모두에서 발생합니다.
- `./initdata.sh` 실행 후에도 동일합니다. 다음 순서로 실행했습니다.
  - `docker-compose down`
  - `./initdata.sh`
  - `docker-compose up --build`
- https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v73-or-later 링크를 참고하여
`cb-apigw/restapigw/deploy/docker-compose.yaml` 파일에서
`user: "1000"` 으로 되어 있는 부분을 `user: "472:0"` 로 바꿔 봤는데도 동일합니다.

**Comment by ccambomorris** [comment]
동일한 상태를 확인하기 위해서 기존 작업 소스가 아니라 https://github.com/cloud-barista/cb-apigw 을 clone 해서 검증을 해 봤습니다.

- 로컬 환경(Mac) 의 docker container & images 모두 삭제
- cb-apigw/restapigw/deploy/initdata.sh 실행 (influxdb, grafana 데이터 초기화) --> 정상
- cb-apigw/restapigw/deploy/docker-compose up --build --> 정상

- 로컬 환경(Mac) 의 docker container & images 모두 삭제
- cb-apigw/initdata.sh 실행 (cb-apigw/restapigw/deploy/initdata.sh 복사)
- cb-apigw/docker-compose up --build --> 정상

새로 클론을 한 상태에서 2가지 docker-compose 를 모두 실행해서 테스트를 했지만 모두 정상적으로 실행되고 있습니다.

제 생각에는 혹시 이전에 실행되었던 컨테이너가 docker-compose down 등으로 제대로 제거되지 않고 남아있어서 Lock 상태가 아닌가 싶습니다.

그래도 docker-compose 를 실행했던 경로에서 `docker-compose down --remove-orphans` 로 고아 상태인 컨테이너들이 존재하는지 검증해 볼 필요가 있어 보입니다.

동일한 상황이 재현되어야 어떤 문제인지를 파악할텐데.. 정상 실행되고 있어서 상황 파악이 힘드네요.
혹시 제가 테스트한 방식에 문제가 있거나 테스트 환경이 다른 점이 있다면 알려주세요.
다시 한번 검증해 보도록 하겠습니다.

**Comment by jihoon-seo** [comment]
~Mac 에서 하셔서 에러가 발생하지 않는 것 같습니다.~

Cloud-Barista 커뮤니티에서는 기본 개발 환경으로 Ubuntu 18.04 를 사용하고 있습니다.

다음과 같이 재현했습니다.

- AWS 도쿄 리전에 Ubuntu 18.04 VM 생성 (`ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210224`)
- `sudo su -` (root 계정으로 변경)
- `git clone https://github.com/cloud-barista/cb-apigw.git`
- `cd cb-apigw/restapigw/deploy/`
- `./initdata.sh`
- `docker-compose up --build`

[결과]
```
# docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                     PORTS
                         NAMES
d535553ed38d        grafana/grafana                   "/run.sh"                2 minutes ago       Exited (1) 2 minutes ago
                         cb-restapigw-grafana

# docker logs d535553ed38d
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
```

- `docker-compose down`
- `./initdata.sh`
- `cd ../..` (CWD: `cb-apigw/`)
- `docker-compose up --build`

[결과]
```
# docker ps -a | grep grafana
d0d5bc299f2e        grafana/grafana                   "/run.sh"                37 seconds ago      Exited (1) 36 seconds ago                                                                                                      etri_grafana

# docker logs d0d5bc299f2e
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

---

[원인]
- 저는 (Docker 사용 시 root 권한이 필요하여, 등등) root 계정으로 작업하고 있습니다.
- `cb-apigw/restapigw/deploy/docker-compose.yaml` 파일의 grafana 부분에 `user: "1000"` 으로 되어 있어서
grafana 컨테이너는 호스트 머신이 보기에는 uid 1000 으로 실행됩니다.
- `./data/influxdb/data:/var/lib/influxdb` 와 같이 볼륨 마운트 되어 있으니
grafana 컨테이너 안의 grafana 바이너리가 grafana 컨테이너 안의 `/var/lib/influxdb` 에 write 시도를 하고
이는 호스트 머신의 `./data/influxdb/data` 에 write 시도를 하는 것인데
uid 1000 으로 `/root` 아래의 디렉토리에 write 를 하려니 퍼미션 에러가 나는 것이었습니다.

[관련]
Docker 및 Docker Compose 를 사용하는 경우에 대해서, 다음의 경우들이 있을 수 있습니다.
1. Non-root, uid == 1000 (+ non-root 사용자에 대해서 Docker 사용 가능하도록 설정)
1. Non-root, uid != 1000 (+ non-root 사용자에 대해서 Docker 사용 가능하도록 설정)
1. root

현재 `cb-apigw/restapigw/deploy/docker-compose.yaml` 파일의 grafana 부분에 `user: "1000"` 으로 되어 있어서
@ccambomorris 님께서 사용하시는 개발 환경은 1번에 해당되어 퍼미션 문제가 발생하지 않았는데
2번이나 3번 환경의 경우 퍼미션 문제가 발생하게 됩니다.

cb-operator 는 root 계정에서 사용하는 것을 전제로 하기 때문에
`docker-compose.yaml` 파일에 `user: "0"` 으로 명시하면 되는데

cb-apigw repo 에는 일반 사용자의 환경을 1번, 2번, 3번 어느 것으로도 가정할 수 없을 것 같아서
고민이 되기는 합니다.
(`cb-apigw/restapigw/deploy/docker-compose.yaml` 파일의 grafana 부분에 `user: ` 를 무엇으로 기재해 놓을 것인가?)

코드 등의 문제는 아니므로 이 이슈는 close 하겠습니다.. ^^

**Comment by ccambomorris** [comment]
네!! 저도 그 부분을 계속 보고 있는 중이었습니다.

처음에 문제가 되어 uid 1000 을 사용했었는데, 지금은 제 로컬에 1000 id를 가지는 사용자가 없는 상태인데 동작을 하고 있고, 472 id도 없지만 지정해도 잘 동작하고,  user 지정을 하지 않아도 정상적으로 잘 동작을 하고 있습니다.

잘 이해가 되지 않고 있습니다. 없는 사용자 ID가 지정되면 소유자 또는 현재 로그인 사용자로 넘기는 것은 아닐것이고, docker 의 실행과 관련해서 설정이 뭔가 다른가 하고 예상하고 있습니다.

여튼 상황에 따라서 특정 사용자를 지정하는 것 보다는 차라리 볼륨 마운트 되는 `.data/grafana/data` 폴더에 모든 쓰기 권한을 주고 처리하는 것이 어떨까 합니다.

제 환경에서는 어떤 상황에서도 동작을 하고 있기 때문에 이 부분에 대한 검증을 해 봐주실 수 있을까요?

**Comment by ccambomorris** [comment]
@jihoon-seo  님이 말씀하신 ubuntu 18.04 버전에서 오류가 발생하는 것을 확인했습니다.

user에 어떤 값을 설정해야 하는지를 결정하기 힘들 것 같으니 아래와 같이 정리할 수 있지 않을까요?

1. grafana 가 사용하는 사용자 grafana (472) 로 호스트의 `./data/grafana/data` 폴더의 소유권을 변경 (이 때 호스트에 해당 사용자가 없어도 상관없음)
  ```bash
  $ chown -R 472:472 ./data/grafana/data
  ```
2. grafana 가 사용하는 마운트 폴더의 모드를 777로 변경
  ```bash
  $ chmod -R 777 ./data/grafana/data
  ```
두 가지 방식 모두 ubuntu 18.04 환경에서 동작하는 것을 확인 했습니다.

위의 같이 둘 중의 하나를 사용하도록 README.md 에 정의하고 `docker-compose.yaml 의 grafana 부분의 user를 제거`하는 것은 어떻까요?

정확한 환경 설정에 대한 부분을 모르는 상태라서 위와 같이 테스트한 결과만 남겨 놓겠습니다.
최종 판단은 구성을 검증하시는 @jihoon-seo  님이 결정하시면 될 것 같습니다. 좋은 방법이 있었으면 좋겠습니다.

**Comment by jihoon-seo** [comment]
> 제 환경에서는 어떤 상황에서도 동작을 하고 있기 때문에 이 부분에 대한 검증을 해 봐주실 수 있을까요?

제가 이슈를 close 하고 바로 VM 을 지워 버렸네요.. ㅠㅠ
다음에 테스트를 해 보겠습니다.. ㅎㅎ

---

Ubuntu 에서 도커를 실행할 때와는 달리
Mac 에서 도커를 실행하면 VM 을 만들고 그 안에 도커를 실행하여 그 도커를 이용하도록 합니다.

- https://tech.ssut.me/docker-on-m1-mac/
- https://junn.net/archives/2323

위의 이유로, 볼륨 마운트 시 퍼미션 문제가
Ubuntu 와 Mac 의 경우가 좀 다를 수 있을 것 같습니다.

---

> 상황에 따라서 특정 사용자를 지정하는 것 보다는 차라리 볼륨 마운트 되는 `./data/grafana/data` 폴더에 모든 쓰기 권한을 주고 처리하는 것이 어떨까 합니다.

`./data/grafana/data` 디렉토리에 777 권한을 주는 것을 git 에도 반영하려고 시도해 보니
`git update-index --chmod=` 에는 `+x` 또는 `-x` 옵션밖에 줄 수 없었습니다.

말씀하신 대로, 사용자에게
Docker Compose 실행 전에 호스트 컴퓨터의 `./data/grafana/data` 디렉토리의 소유권이나 모드를 바꾸도록
가이드하는 방법 밖에는 없을 것 같습니다.

문제를 확인하고 공유해 주셔서 감사합니다.. ^^
