### ISSUE TITLE
conf/apis/*.yaml 파일 수정 시 restapigw 강제 종료됨

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-apigw#52]
@ccambomorris 한 번 확인을 부탁드립니다.. ^^

**What happened**
: 
`conf/apis/*.yaml` 파일 수정 시 restapigw 강제 종료됨

**What you expected to happen**
: 
`conf/apis/*.yaml` 파일 수정 시 restapigw 강제 종료되지 않음

**How to reproduce it (as minimally and precisely as possible)**
: 
- cb-restapigw 0.3.4 컨테이너 이미지로 실행 
  - 저는 cb-operator 를 이용했습니다.
  - [cb-apigw/docker-compose.yaml](https://github.com/cloud-barista/cb-apigw/blob/master/docker-compose.yaml) 또는 [cb-apigw/restapigw/deploy/docker-compose.yaml](https://github.com/cloud-barista/cb-apigw/blob/master/restapigw/deploy/docker-compose.yaml) 를 이용해도 동일한 에러가 발생할 것으로 예상됩니다.
- 개발 환경의 에디터를 이용하여 `conf/apis/dev-test.yaml` 파일을 다음과 같이 수정
  - `http://localhost:8100` => `http://fake_api:8100`
  - (반대 방향으로 수정해도 동일한 에러 발생)

```
❯ docker logs cb-restapigw

...
[GIN-debug] CONNECT /inventory/*bypass        --> github.com/cloud-barista/cb-apigw/restapigw/pkg/middlewares/opencensus/router/gin.(*handler).HandlerFunc-fm (3 handlers)
[GIN-debug] TRACE  /inventory/*bypass        --> github.com/cloud-barista/cb-apigw/restapigw/pkg/middlewares/opencensus/router/gin.(*handler).HandlerFunc-fm (3 handlers)
[CLOUD-BARISTA].[INFO]: 2021-04-12 07:50:50 router.go:160, github.com/cloud-barista/cb-apigw/restapigw/pkg/router/gin.(*PipeConfig).RegisterAPIs() - [API G/W] API Endpoints loaded 
[CLOUD-BARISTA].[INFO]: 2021-04-12 07:50:50 server.go:292, github.com/cloud-barista/cb-apigw/restapigw/pkg/server.(*Server).StartWithContext() - [SERVER] Started 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcb55e5]

goroutine 48 [running]:
github.com/cloud-barista/cb-apigw/restapigw/pkg/api.parseEndpoint(0xc0001b4800, 0xc000135400, 0x0, 0x200, 0x200, 0x0, 0x0)
        /app/pkg/api/repository.go:92 +0xa5
github.com/cloud-barista/cb-apigw/restapigw/pkg/api.(*FileSystemRepository).Watch.func1(0xc000634660, 0xc0006370e0, 0x1597ac0, 0xc0000c1e80)
        /app/pkg/api/file_repository.go:85 +0x471
created by github.com/cloud-barista/cb-apigw/restapigw/pkg/api.(*FileSystemRepository).Watch
        /app/pkg/api/file_repository.go:72 +0x5d
```

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: v0.3.4 (8b3d980)
- OS: Ubuntu 18.04
- Others: 

**Proposed solution**
: 

**Any other context**
:
- 이 문제를 수정하는 PR이 이전에 있었습니다. (#43)

**Comment by ccambomorris** [comment]
@jihoon-seo 오류 상황 확인하였습니다.

우선 Mac 개발 환경에서는 역시 잘 동작을 하고 있습니다. 
지난 주에 테스트 했던 ubuntu 에서는 알려주신 것과 같이 오류가 발생하고 있습니다.

논리적인 원인 파악 결과는 변경이 발생한 파일의 내용들을 yarml 데이터 unmarshal 처리한 결과가 nil인 것으로 보입니다.
이전 PR (#43 )을 적용했을 때는 이런 상황이 없었던 것인가요? 

이 부분은 검증하기 위해서는 ubuntu 상에 실제 개발 환경을 구축하고 Debugging을 해 봐야 할 것 같습니다.
환경 구성과 Debugging으로 약간 시간이 걸릴 듯 합니다.

**Comment by jihoon-seo** [comment]
@ccambomorris 안녕하세요

> 이전 PR (#43 )을 적용했을 때는 이런 상황이 없었던 것인가요?

#43 머지 직후에는 이 건에 대한 테스트를 해 보지 못하고 있다가, 이번에 발견하게 되었습니다.

> 이 부분은 검증하기 위해서는 ubuntu 상에 실제 개발 환경을 구축하고 Debugging을 해 봐야 할 것 같습니다.
환경 구성과 Debugging으로 약간 시간이 걸릴 듯 합니다.

네 알겠습니다.. ^^

---

좀 다른 이야기인데요,
https://github.com/cloud-barista/cb-apigw/pull/45/files#diff-fced641d0b1621513270c805e84fb194f32a8c38db4ecbad517f2a6a7a962963R15 에서
`"gopkg.in/yaml.v3"` 를 `"gopkg.in/yaml.v2"` 로 바꾸셨었습니다.
혹시 구버전으로 바꾼 이유가 무엇인지 알 수 있을까요?

**Comment by ccambomorris** [comment]
@jihoon-seo 

`gopkg.in/yaml.v3` 를 쓰는게 맞습니다.

vscode 상에서 개발을 할때 yaml 관련 소스를 수정하면 `gopkg.in/yaml.v2`  로 가끔  자동 지정되는 문제가 있어서 수정 작업을 했었는데 이번에 미처 확인을 못하고 commit 이 된 듯 합니다.

이번에 오류 상황을 해결하면서 v3 버전으로 재 구성해서 PR 하도록 하겠습니다. ^^ (설마 이것 때문이라면 ... 아니겠지요.)

**Comment by ccambomorris** [comment]
@jihoon-seo 

ubuntu 환경에서 파일 변경 했을 경우에 cb-apigw 가 종료되는 현상에 대한 처리를 하였습니다.

[원인]
파일을 변경 저장하는 방식에 차이로 인해서 파일 변경에 대한 이벤트가 2번 발생합니다.
- 파일 저장 (이 떄 실제 파일에는 내용이 없습니다.)
- 파일 내용 저장 (이때 정상적으로 내용이 존재합니다.)

[해결]
근본적인 해결을 위해서 관련한 정보를 검색해 보았지만, 
현재까지는 근본적으로 해결할 수 있는 의미있는 자료를 찾지 못한 상태이며,
대 부분은 OS 별로 사용한 에디터의 파일 저장 방식의 차이로 보인다는 의견과 
`github.com/fsnotify/fsnotify` 패키지의 이슈 제기가 된 상태라는 것입니다.

일단 처리는 변경 이벤트를 받고 해당 파일을 읽었을 때 내용이 없는 상태라면 Skip 하는 방식으로 처리를 했습니다.

내용 확인해 보시고, 다른 방식 또는 접근 방법에 대한 의견을 주시면 검토해 보겠습니다.

일단 상기와 같이 문제를 회피하는 방식을 적용한 상태로 PR을 올리도록 하겠습니다.

**Comment by jihoon-seo** [comment]
Resolved by #54
